"""Add show_for_guest to categories

Revision ID: 0da98b72b7bd
Revises: 25e41d1a7b0f
Create Date: 2026-02-18 02:08:08.801174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da98b72b7bd'
down_revision: Union[str, Sequence[str], None] = '25e41d1a7b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('show_for_guest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'show_for_guest')
    # ### end Alembic commands ###
