"""user data

Revision ID: 1d9dc121301b
Revises: 1f43c69cbade
Create Date: 2026-03-11 00:22:17.807587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9dc121301b'
down_revision: Union[str, Sequence[str], None] = '1f43c69cbade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_categories_group_id'), table_name='categories')
    op.drop_constraint(op.f('document_files_document_id_fkey'), 'document_files', type_='foreignkey')
    op.create_foreign_key(None, 'document_files', 'documents', ['document_id'], ['id'])
    op.drop_constraint(op.f('document_tags_tag_id_fkey'), 'document_tags', type_='foreignkey')
    op.drop_constraint(op.f('document_tags_document_id_fkey'), 'document_tags', type_='foreignkey')
    op.create_foreign_key(None, 'document_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'document_tags', 'documents', ['document_id'], ['id'])
    op.drop_index(op.f('idx_documents_category_id'), table_name='documents')
    op.drop_index(op.f('idx_documents_code_trgm'), table_name='documents', postgresql_ops={'code': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_documents_name_trgm'), table_name='documents', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_pages_designation_trgm'), table_name='pages', postgresql_ops={'designation': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_pages_document_id'), table_name='pages')
    op.drop_index(op.f('idx_pages_name_trgm'), table_name='pages', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'groups', ['department_id'], ['id'])
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.create_index(op.f('idx_pages_name_trgm'), 'pages', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_pages_document_id'), 'pages', ['document_id'], unique=False)
    op.create_index(op.f('idx_pages_designation_trgm'), 'pages', ['designation'], unique=False, postgresql_ops={'designation': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_documents_name_trgm'), 'documents', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_documents_code_trgm'), 'documents', ['code'], unique=False, postgresql_ops={'code': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_documents_category_id'), 'documents', ['category_id'], unique=False)
    op.drop_constraint(None, 'document_tags', type_='foreignkey')
    op.drop_constraint(None, 'document_tags', type_='foreignkey')
    op.create_foreign_key(op.f('document_tags_document_id_fkey'), 'document_tags', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('document_tags_tag_id_fkey'), 'document_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'document_files', type_='foreignkey')
    op.create_foreign_key(op.f('document_files_document_id_fkey'), 'document_files', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_categories_group_id'), 'categories', ['group_id'], unique=False)
    # ### end Alembic commands ###
