"""Add show_for_guest to groups

Revision ID: 25e41d1a7b0f
Revises: e52d659d3c50
Create Date: 2026-02-18 00:54:04.579649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e41d1a7b0f'
down_revision: Union[str, Sequence[str], None] = 'e52d659d3c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('show_for_guest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'show_for_guest')
    # ### end Alembic commands ###
