"""Change reset_token logic

Revision ID: a3f898070343
Revises: e93f2a105d41
Create Date: 2025-12-08 15:28:22.182791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f898070343'
down_revision: Union[str, Sequence[str], None] = 'e93f2a105d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.drop_constraint(op.f('verification_codes_reset_token_key'), 'verification_codes', type_='unique')
    op.drop_column('verification_codes', 'reset_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('verification_codes_reset_token_key'), 'verification_codes', ['reset_token'], postgresql_nulls_not_distinct=False)
    op.drop_table('reset_tokens')
    # ### end Alembic commands ###
