"""Add cascade delete to document_files

Revision ID: ae2f6293ca2d
Revises: d94fac64bccf
Create Date: 2026-02-26 15:55:23.114743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2f6293ca2d'
down_revision: Union[str, Sequence[str], None] = 'd94fac64bccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_files_document_id_fkey'), 'document_files', type_='foreignkey')
    op.create_foreign_key(None, 'document_files', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_files', type_='foreignkey')
    op.create_foreign_key(op.f('document_files_document_id_fkey'), 'document_files', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
