"""Set server_default for refresh_tokens created_at

Revision ID: bb954525de38
Revises: 8c0ef1c6191d
Create Date: 2025-12-06 10:46:19.574481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb954525de38'
down_revision: Union[str, Sequence[str], None] = '8c0ef1c6191d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
