"""Changes in the verification_codes table

Revision ID: c4561d805f60
Revises: 6fbca8713be4
Create Date: 2025-12-10 12:36:22.738592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4561d805f60'
down_revision: Union[str, Sequence[str], None] = '6fbca8713be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('email', sa.String(100), nullable=False))
    op.add_column('verification_codes', sa.Column('code_hash', sa.String(), nullable=False))
    op.drop_constraint(op.f('verification_codes_code_key'), 'verification_codes', type_='unique')
    op.create_unique_constraint(None, 'verification_codes', ['code_hash'])
    op.drop_constraint(op.f('verification_codes_user_id_fkey'), 'verification_codes', type_='foreignkey')
    op.create_foreign_key('fk_verification_codes_email', 'verification_codes', 'users', ['email'], ['email'])
    op.drop_column('verification_codes', 'user_id')
    op.drop_column('verification_codes', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('verification_codes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_verification_codes_email', 'verification_codes', type_='foreignkey')
    op.create_foreign_key(op.f('verification_codes_user_id_fkey'), 'verification_codes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'verification_codes', type_='unique')
    op.create_unique_constraint(op.f('verification_codes_code_key'), 'verification_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('verification_codes', 'code_hash')
    op.drop_column('verification_codes', 'email')
    # ### end Alembic commands ###
