"""Add cascade delete to document_tags

Revision ID: d94fac64bccf
Revises: 1f43c69cbade
Create Date: 2026-02-26 15:52:44.282113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94fac64bccf'
down_revision: Union[str, Sequence[str], None] = '1f43c69cbade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_tags_tag_id_fkey'), 'document_tags', type_='foreignkey')
    op.drop_constraint(op.f('document_tags_document_id_fkey'), 'document_tags', type_='foreignkey')
    op.create_foreign_key(None, 'document_tags', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_tags', type_='foreignkey')
    op.drop_constraint(None, 'document_tags', type_='foreignkey')
    op.create_foreign_key(op.f('document_tags_document_id_fkey'), 'document_tags', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('document_tags_tag_id_fkey'), 'document_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
