"""Add has_all_docs_search to groups

Revision ID: e52d659d3c50
Revises: b42172f3bd7a
Create Date: 2026-02-17 00:52:37.366132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52d659d3c50'
down_revision: Union[str, Sequence[str], None] = 'b42172f3bd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('has_all_docs_search', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'has_all_docs_search')
    # ### end Alembic commands ###
