"""Added a reset_token to VerificationCode model

Revision ID: e93f2a105d41
Revises: 3ffdb65207f9
Create Date: 2025-12-08 15:00:44.799765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93f2a105d41'
down_revision: Union[str, Sequence[str], None] = '3ffdb65207f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('reset_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'verification_codes', ['reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_codes', type_='unique')
    op.drop_column('verification_codes', 'reset_token')
    # ### end Alembic commands ###
